# Generated by Django 5.2.4 on 2025-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
