# Generated by Django 5.2.5 on 2025-08-21 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0002_place_dong"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="dong",
        ),
    ]
