# Generated by Django 5.2.4 on 2025-08-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_alter_place_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="longtitude",
            new_name="long",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="place_name",
            new_name="name",
        ),
    ]
