# Generated by Django 5.2 on 2025-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="is_anonymouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_anonymouse",
            field=models.BooleanField(default=False),
        ),
    ]
