# Generated by Django 5.2 on 2025-05-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_comment_is_anonymouse_alter_post_is_anonymouse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="is_anonymouse",
            new_name="is_anonymous",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="is_anonymouse",
            new_name="is_anonymous",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
        ),
    ]
