# Generated by Django 5.2 on 2025-06-29 09:41

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_like_post_like_scrap_post_scrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=posts.models.upload_filepath),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, upload_to=posts.models.upload_filepath),
        ),
    ]
