# Generated by Django 5.2 on 2025-08-04 12:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to=users.models.upload_filepath),
        ),
    ]
