# Generated by Django 5.2.5 on 2025-08-20 17:14

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_positive", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to=post.models.upload_filepath)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("AI_matching", models.TextField(blank=True)),
                (
                    "video",
                    models.FileField(blank=True, upload_to=post.models.upload_filepath),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recom_now", models.TextField(blank=True)),
                ("recom_later", models.TextField(blank=True, default="")),
                ("comment", models.TextField(blank=True)),
                ("is_complete", models.BooleanField(default=False)),
            ],
        ),
    ]
