# Generated by Django 5.2.4 on 2025-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="matching_rate",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="AI_matching",
            field=models.TextField(blank=True),
        ),
    ]
