# Generated by Django 5.2.4 on 2025-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_matching_rate_alter_post_ai_matching"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="matching_rate",
            field=models.IntegerField(default=0),
        ),
    ]
