# Generated by Django 5.2.4 on 2025-08-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_matching_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="matching_rate",
            field=models.BooleanField(default=False),
        ),
    ]
