# Generated by Django 5.2.5 on 2025-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="address_jibun",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="address_road",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
