# Generated by Django 5.2.5 on 2025-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_post_address_post_address_jibun_post_address_road"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dong",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
