# Generated by Django 5.2.4 on 2025-08-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_remove_post_matching_rate_aifeedback_todolist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
