# Generated by Django 5.2.5 on 2025-08-21 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_post_dong"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="address_road",
        ),
    ]
