# Generated by Django 5.2.4 on 2025-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
        ("post", "0006_todolist_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="place",
            field=models.ManyToManyField(related_name="post_place", to="map.place"),
        ),
    ]
