# Generated by Django 5.2.4 on 2025-08-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_post_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="comment",
        ),
    ]
