# Generated by Django 5.2.4 on 2025-08-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_remove_todolist_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="post",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todolist",
                to="post.post",
            ),
        ),
    ]
