# Generated by Django 5.2.4 on 2025-08-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_todolist_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommend",
            name="todo_list",
        ),
        migrations.AddField(
            model_name="recommend",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="recommend",
            name="recom_later",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.DeleteModel(
            name="TodoList",
        ),
    ]
