# Generated by Django 5.2.4 on 2025-08-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_remove_recommend_todo_list_recommend_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="scrab",
        ),
    ]
