# Generated by Django 5.2.4 on 2025-08-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0013_category_post_latitude_post_longitude_post_video_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcategory",
            name="category",
        ),
        migrations.RemoveField(
            model_name="postcategory",
            name="post",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="PostCategory",
        ),
    ]
