# Generated by Django 5.2.4 on 2025-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0014_remove_postcategory_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="address_jibun",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="dong",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
